baseURL = 'https://cleivervx.github.io'
languageCode = 'pt-br'
title = 'cleiversouza.tech'
#theme = "hugo-blog-awesome"
theme = "hermit-v2"
autor = 'Cleiver Souza'
copyright = 'cleiversouza.tech'
enableRobotsTXT = true
#publishDir = "docs"

[module]
  [[module.imports]]
    path = "https://github.com/hugo-sid/hugo-blog-awesome"
    disable = false